---
- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
